# Generated by Django 2.1.3 on 2018-11-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_datastorebase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataStoreBase',
        ),
    ]
