# Generated by Django 2.0.9 on 2018-11-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_delete_datastorebase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mapas',
        ),
    ]
