# Generated by Django 2.0.9 on 2018-11-26 13:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_delete_mapas'),
    ]

    operations = [
        migrations.CreateModel(
            name='mapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Maps',
                'verbose_name': 'Map',
            },
        ),
    ]
