# Generated by Django 2.0.9 on 2018-11-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_worldborder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldborder',
            old_name='mpoly',
            new_name='geom',
        ),
    ]
