# Generated by Django 2.0.9 on 2018-11-26 14:18

from django.db import migrations, models
import maps.validators


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20181126_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapServerColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.IntegerField(blank=True, null=True, validators=[maps.validators.validate_integer_color])),
                ('green', models.IntegerField(blank=True, null=True, validators=[maps.validators.validate_integer_color])),
                ('blue', models.IntegerField(blank=True, null=True, validators=[maps.validators.validate_integer_color])),
                ('hex_string', models.CharField(blank=True, max_length=9, validators=[maps.validators.validate_hex_color])),
                ('attribute', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
