# Generated by Django 2.0.9 on 2018-11-26 15:06

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_mapservercolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier.', max_length=255)),
                ('status', models.SmallIntegerField()),
                ('projection', models.PositiveSmallIntegerField(default=4326, help_text='EPSG code of the map projection')),
                ('size', models.CharField(help_text='Map size in pixel units', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
    ]
