# Generated by Django 2.0.9 on 2018-11-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_mapobj_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobj',
            name='image_color',
            field=models.ForeignKey(blank=True, help_text='Initial map background color.', null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.MapServerColor'),
        ),
    ]
