# Generated by Django 2.0.9 on 2018-11-26 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_mapobj_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapobj',
            name='countries',
        ),
        migrations.AddField(
            model_name='mapobj',
            name='countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.WorldBorder'),
        ),
    ]
