# Generated by Django 2.0.9 on 2018-11-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_auto_20181126_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapobj',
            name='countries',
        ),
    ]
