# Generated by Django 2.0.9 on 2018-11-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_remove_mapobj_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldborder',
            name='mapobjs',
            field=models.ManyToManyField(blank=True, null=True, to='maps.MapObj'),
        ),
    ]
